### ISSUE TITLE
Set custom bearer authorization header for axios instance

### ISSUE THREAD

**Issue by moswil** [chinesedfan/You-Dont-Know-Axios#5]
Can you please respond to this [StackOver question](https://stackoverflow.com/questions/63309952/axios-extracting-http-cookies-and-setting-them-as-authorization-headers?stw=2)

The main aim is to set a Bearer Authorization header, which can be used to access backend protected resources.

```
Authorization: Bearer <accessToken>
```

The **accessToken** is stored in an HttpOnly cookie.

Thanks.

**Comment by chinesedfan** [comment]
> Welcome everyone to open issue or pull request to give suggestions for this document. But don't ask axios questions here.

I will reply your SO question directly.
